### ISSUE TITLE
I want to help, where to find a guide on what is needed or who to talk to?

### ISSUE THREAD

**Issue by rafmst** [ONEARMY/project-kamp#6]
Hi! My name is Rafael, I'm portuguese developer but I work and live in Norway. I would like to help with coding voluntarily since I have a 9-5 work already. The first thing I notice is that the code/technology could be modernised, like converted to React or something.

Let me know who to talk to :D

**Comment by benfurber** [comment]
Hey @rafatrace, welcome! The video team added the wrong repo link, the main repo is https://github.com/ONEARMY/community-platform/. Hope to see you there shortly! :)
